# yaml-language-server: =https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Igoravl.TfsCmdlets
PackageVersion: 2.1.3.2589
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: user
  InstallerUrl: https://github.com/igoravl/TfsCmdlets/releases/download/v2.1.3%2B2589.4/TfsCmdlets-2.1.3.msi
  InstallerSha256: A19BD5BF230B3873B9EB90E19FC6E0C5C3D1DE0F6628EEDFBC14043643986FEB
  InstallerSwitches:
    Silent: /qn
    SilentWithProgress: /qb
  ProductCode: "{BB89246B-D110-4ACC-B83A-CB235C4BC954}"
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

