# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: ElijahLopez.MusicCaster
PackageVersion: 4.90.95
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- https
- http
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/elibroftw/music-caster/releases/download/v4.90.95/Music.Caster.Setup.exe
  InstallerSha256: 617B68E360AF228D3E68BFE4E1C90D3786E82E45DA35766F257984E2E54D52DE
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
