# Automatically updated by the winget bot at 2021/Sep/01
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.96.1061.0
MinimumOSVersion: 8.1.0.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
    MinimumVersion: 92.0.902.84
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  InstallerType: exe
  InstallerSha256: 14F081547BC90DB390FB4CF8FE31DBE2C06AB03666D5B7FEE6B7F736380468E3
  Scope: machine
  InstallerSwitches:
    Custom: -norestart ACCEPT_EULA=1
    Silent: -quiet
    SilentWithProgress: -passive
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup.exe
  InstallerType: exe
  InstallerSha256: C9D2F845487450BA4B2AC534DE55D924EB4960A4D58FB8626727241DDD6446E8
  Scope: machine
  InstallerSwitches:
    Custom: -norestart ACCEPT_EULA=1
    Silent: -quiet
    SilentWithProgress: -passive
ManifestType: installer
ManifestVersion: 1.0.0
