# Automatically updated by the winget bot at 2021/Sep/21
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Axosoft.GitKraken
PackageVersion: 8.0.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://release.axocdn.com/win64/GitKrakenSetup.exe
  InstallerSha256: E655DFADE77837DF7793BE92CD4CC99FF8D469D98E97A97C8B9D52C6A1F12C77
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  UpgradeBehavior: install
- Platform:
  - Windows.Desktop
  InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://release.axocdn.com/win32/GitKrakenSetup.exe
  InstallerSha256: B1DC53D11D7B305B6C8ECC91686895B3AF327E43943933F8246674A92BE41EB0
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
