# Automatically updated by the winget bot at 2021/Sep/24
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Microstockr.Desktopapp
PackageVersion: 2.3.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://microstockr.com/downloads/MicrostockrSetup.exe
  InstallerSha256: 45307DF5122059862A5D0478E3A87E71CB70E2CF72EF4AE8D15A786FC600EDB8
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
