# Automatically updated by the winget bot at 2021/Nov/25
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Belarc.Advisor
PackageVersion: 11.1.0.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.belarc.com/advisor/advisorinstaller.exe
  InstallerSha256: 35A2905EC1463F3D72837FF7248D77EADF4A47DD90A5F4D95CB401269AAE33E6
ManifestType: installer
ManifestVersion: 1.0.0
