# Automatically updated by the winget bot at 2021/Sep/17
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Miro.Miro
PackageVersion: 0.6.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.miro.com/platforms/win32/Miro.exe
  InstallerSha256: 21DF9E005464A61245D5ED8347926F1F28F455238A6A5033A868EDA93BBBECF3
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.miro.com/platforms/win32-x86/Miro.exe
  InstallerSha256: DBD4F52341CC8AF8003476AEAAF0B0BD8C180FBE0D636B87E84BFF60E05F46E2
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
