# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BitSum.ProcessLasso.Beta
PackageVersion: 10.3.0.21
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
  InstallerSha256: 83A04CD6510731862CCF84968AB3EDDCD34DAD47E50AB28AE453CAD593ED5841
ManifestType: installer
ManifestVersion: 1.0.0
