# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json
PackageIdentifier: Google.Chrome
PackageVersion: 96.0.4664.110
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: AF34A0DCC187838FCB71DB3BF7CA0D02333E5607379C8FBEEA44EF4A69AA25C5
  ProductCode: "{177B605A-B1E1-3197-B5D4-05F00C0174D1}"
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: D6B0E020E0318FECA663C3079C8B3B60DBB1F0B7C77142394AA6D77FD679B42D
  ProductCode: "{9175B420-1EC1-3693-99C3-91B5413D40E1}"
ManifestType: installer
ManifestVersion: 1.1.0

