# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: valinet.ExplorerPatcher.Prerelease
PackageVersion: 22000.348.40.11
MinimumOSVersion: 10.0.0.0
InstallerType: inno
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/valinet/ExplorerPatcher/releases/download/22000.348.40.11_94db02b/ep_setup.exe
  InstallerSha256: B311D9899380A032536F655E1F442A055B7F07FCA7F0782C16455288806E8D10
  ProductCode: '{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_ExplorerPatcher'
ManifestType: installer
ManifestVersion: 1.1.0
