# Automatically updated by the winget bot at 2021/Sep/16
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: LogMeIn.LastPass
PackageVersion: 4.80.0.2236
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.cloud.lastpass.com/windows_installer/LastPassInstaller.msi
  InstallerSha256: 117FE73FEE2A72593A57FD1EA224E1FD7FDDB0814F00561E9E42AA8052DC598E
  ProductCode: "{217DE51C-82EB-49BF-811F-71917F290FFA}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
