# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Garmin.GarminExpress
PackageVersion: 7.8.1.0
PackageLocale: en-US
Publisher: Garmin Ltd or its subsidiaries
PublisherUrl: https://www.garmin.com
PublisherSupportUrl: https://support.garmin.com
PrivacyUrl: https://www.garmin.com/privacy/cookies/policy/
Author: Garmin Ltd
PackageName: Garmin Express
PackageUrl: https://www.garmin.com/software/express/windows/
License: Proprietary
# LicenseUrl: 
Copyright: Copyright (c) Garmin Ltd All rights reserved.
# CopyrightUrl: 
ShortDescription: Easily update maps and software, sync with Garmin Connect™ and register your device.
# Description: 
# Moniker: 
# Tags: 
ManifestType: defaultLocale
ManifestVersion: 1.0.0
