# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Garmin.GarminExpress
PackageVersion: 7.8.1.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://download.garmin.com/omt/express/GarminExpress.exe
  InstallerSha256: 64BA997C63C877C19426762EEB8FA7CC81F10338D313065A9A389B66052B4E38
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
