# Created using wingetcreate 0.4.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json

PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 10.0.2914.0
PackageLocale: en-US
Publisher: SmartSoft Ltd.
PublisherUrl: https://www.smartftp.com
PublisherSupportUrl: https://www.smartftp.com/support
Author: SmartSoft Ltd.
PackageName: SmartFTP Client
License: Commercial
LicenseUrl: https://www.smartftp.com/static/Products/Client/License.txt
ShortDescription: SmartFTP is a fast and reliable FTP, FTPS, SFTP, HTTP, Amazon S3, WebDAV, Google Drive, Google Cloud Storage, Microsoft OneDrive, Backblaze B2, Telnet, Terminal client with lots of features and a modern user interface.
Moniker: smartftp
Tags:
- ftp
- sftp
- webdav
- onedrive
- gdrive
- ssh
MinimumOSVersion: 10.0.14393.0
Installers:
- InstallerLocale: en-US
  Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://static.smartftp.com/static/Products/Client/10.0.2914.0/x64/SmartFTP.msi
  InstallerSha256: E65778A334BB409E4EB6F6A2ED823C984E6D598DE2FCE7F0F04B93C29531C1A1
  ProductCode: '{4B20860F-6741-4A0A-80C1-1E3BD682422F}'
ManifestType: singleton
ManifestVersion: 1.0.0

