# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.21.8
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup_x64.exe
  InstallerSha256: A379AB9F4C24673F5BE5C167F4E19A2A0105B95ECF7392562BFFB4B81107871C
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup.exe
  InstallerSha256: 49D968B19281C16BC2C123CFF88B5FC00314BCA1381F93CEDEB42749B3D72B91
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

