# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.2019.Community
PackageVersion: 16.11.2
PackageName: Visual Studio Community 2019
Author: Microsoft
Publisher: Microsoft Corporation
ShortDescription: The Community edition of Visual Studio, an integrated development environment (IDE) from Microsoft.  Individual developers have no restrictions on their use of the Community edition.
PackageUrl: https://visualstudio.microsoft.com/
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://visualstudio.microsoft.com/license-terms/
Moniker: vs2019-community
Tags:
- C++
- vs
- C#
Commands:
- devenv
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/bacf7555-1a20-4bf4-ae4d-1003bbc25da8/7fed4a771c7f2dc94a765234814a0d8902db2b79fd810389897f2249bd5aefb5/vs_Community.exe
  InstallerSha256: 7FED4A771C7F2DC94A765234814A0D8902DB2B79FD810389897F2249BD5AEFB5
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --passive
    Custom: --wait --productId Microsoft.VisualStudio.Product.Community --channelId VisualStudio.16.Release --channelUri https://aka.ms/vs/16/release/channel --add Microsoft.VisualStudio.Workload.Universal
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

