# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Microsoft.XMLNotepad
PackageVersion: 2.8.0.49
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: msix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- xml
Installers:
- Platform:
  - Windows.Universal
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: neutral
  InstallerUrl: https://github.com/microsoft/XmlNotepad/releases/download/2.8.0.49/XmlNotepadPackage_2.8.0.49_AnyCPU.msixbundle
  InstallerSha256: E0BAF5561758F278A316340F0696505EF2EB8FDACB3BE2BE2D670288FED4DABF
  SignatureSha256: 199FA505A0A319A932439B96033420026FCD06CB6F7A7D7578664A290FF3856D
  PackageFamilyName: 5632ff08-aa93-439a-b09f-677eb3664250_b2j8apzf1bbh6
ManifestType: installer
ManifestVersion: 1.0.0

