# Automatically updated by the winget bot at 2021/Sep/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: KCSoftwares.SUMo
PackageVersion: 5.14.0.505
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- txt
- csv
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://kcsoftwares.com/files/sumo_lite.exe
  InstallerSha256: 2D249FAAB11F2F7F8C2A6E2BF7674B0F56F8F7D4DA504C31645199FBA72FE89D
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
