# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=QUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.kile
PackageVersion: 2.9.93
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
FileExtensions:
- tex
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kile_Release_win64/1397/artifact/kile-2.9.93-1397-windows-msvc2019_64-cl.exe
  InstallerSha256: B08C528197D5A27BA8374D95FD934E1692019BBA20176547FB265552264420AF
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kile_Release_win64/1397/artifact/kile-2.9.93-1397-windows-msvc2019_64-cl.exe
  InstallerSha256: B08C528197D5A27BA8374D95FD934E1692019BBA20176547FB265552264420AF
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
