# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Freeplane.Freeplane
PackageVersion: 1.9.8
PackageLocale: en-US
Publisher: Open source
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: Freeplane
PackageUrl: https://www.freeplane.org/
License: GNU General Public License, Version 2
# LicenseUrl: 
Copyright: Copyright © 2000-2021 Freeplane team and others
# CopyrightUrl: 
ShortDescription: Free mind mapping software. Fast. Simple. Streamlined.
# Description: 
Moniker: freeplane
Tags:
- map
- mapping
- mindmapping
- mind-mapping
ManifestType: defaultLocale
ManifestVersion: 1.0.0
