# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Freeplane.Freeplane
PackageVersion: 1.9.8
MinimumOSVersion: 10.0.0.0
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-1.9.8.exe/download
  InstallerSha256: E7E583E678CD9CCB63969D314160A0D2B3F897E3FBEBFD1FEA602CA13BA3F19A
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
