# Automatically updated by the winget bot at 2021/Sep/22
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: SFLinux.Jami
PackageVersion: 1.0.7934.40122
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://dl.jami.net/windows/jami.release.x64.msi
  InstallerSha256: D2AE60E087F6E292CD3784AC11D841E482E80696CEC410A0151CA582A9F7829B
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
