# Created with YamlCreate.ps1 v2.0.4 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: JetBrains.Space
PackageVersion: 2021.4.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/space/jetbrains-space.exe
  InstallerSha256: E84FB1CA81F96801E04AAF13DC4F17E76DAEBB63E68BC08483A3FE93E0616BE4
ManifestType: installer
ManifestVersion: 1.1.0
