# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: EdrawSoft.EdrawMind
PackageVersion: 9.0.6.155
PackageLocale: en-US
Publisher: EdrawSoft Co.,Ltd.
PublisherUrl: https://www.edrawsoft.com/
PublisherSupportUrl: https://www.edrawsoft.com/support.html
PrivacyUrl: https://www.edrawsoft.com/privacy-policy.html
# Author: 
PackageName: EdrawMind
PackageUrl: https://www.edrawsoft.com/edrawmind/
License: Proprietary
LicenseUrl: https://www.edrawsoft.com/user-license-agreement.html
# Copyright: 
# CopyrightUrl: 
ShortDescription: A full-featured collaborative mind mapping and brainstorming tool
# Description: 
# Moniker: 
# Tags: 
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
