# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json
PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.78.765.g5ea20b00
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: /Silent
  SilentWithProgress: /Silent
UpgradeBehavior: install
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x86
  InstallerUrl: https://download.scdn.co/SpotifyFullSetup.exe
  InstallerSha256: 74F3E5EA717A79AD18BBC42D0CE4A59CBF67FF7A4CC49271D321C9EC4DFDEEE7
ManifestType: installer
ManifestVersion: 1.1.0

