# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: lyswhut.lx-music-desktop
PackageVersion: 1.13.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.13.0/lx-music-desktop-v1.13.0-x64-Setup.exe
  InstallerSha256: CF1BADBC71748DCE88A8D593E1B9C6CF8B7DC3212C55A2B6E29391CA31D31FBC
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.13.0/lx-music-desktop-v1.13.0-x64-Setup.exe
  InstallerSha256: CF1BADBC71748DCE88A8D593E1B9C6CF8B7DC3212C55A2B6E29391CA31D31FBC
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.13.0/lx-music-desktop-v1.13.0-x86-Setup.exe
  InstallerSha256: 03E5AF3F4C754DB13B69D4D7001DC58BBAA415A4549F008003BFA8FB26E9C05A
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.13.0/lx-music-desktop-v1.13.0-x86-Setup.exe
  InstallerSha256: 03E5AF3F4C754DB13B69D4D7001DC58BBAA415A4549F008003BFA8FB26E9C05A
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.13.0/lx-music-desktop-v1.13.0-arm64-Setup.exe
  InstallerSha256: 941DB1859A2DDAA42CE884D70E94F53D48199B72C4BA6C03038762007CF19807
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.13.0/lx-music-desktop-v1.13.0-arm64-Setup.exe
  InstallerSha256: 941DB1859A2DDAA42CE884D70E94F53D48199B72C4BA6C03038762007CF19807
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
