# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Figma.Figma
PackageVersion: 101.6.0
PackageLocale: en-US
Publisher: Figma, Inc.
PublisherUrl: https://www.figma.com
#PublisherSupportUrl: https://help.figma.com/hc/en-us
PrivacyUrl: https://www.figma.com/summary-of-policy/
Author: Figma, Inc.
PackageName: Figma
PackageUrl: https://www.figma.com
License: Proprietary
Copyright: Copyright (c) Figma Inc
ShortDescription: The collaborative interface design tool Build better products as a team. Design, prototype, and gather feedback all in one place with Figma.
Moniker: figma
ManifestType: defaultLocale
ManifestVersion: 1.0.0
