# Automatically updated by the winget bot at 2021/Sep/22
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Termius.Termius
PackageVersion: 7.21.1
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Protocols:
- ssh
- telnet
- http
FileExtensions:
- ppk
- pem
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://autoupdate.termius.com/windows/Termius.exe
  InstallerSha256: A77B652B7EB844A8FB78538A5E059C4F86D28516C6F2406801AFA6DD4F851E7C
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
