# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Nvidia.GeForceNow
PackageVersion: 2.0.33.112
MinimumOSVersion: 10.0.0.0
InstallerSuccessCodes:
- "3858759680"
Platform:
- Windows.Desktop
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download.nvidia.com/gfnpc/GeForceNOW-release.exe
  InstallerSha256: E208AB4EC0A7A5AA8BE981EDC94CA57C6C605D7C0567CB54242630BC37C045F4
  InstallerSwitches:
    Silent: -s
    SilentWithProgress: -s
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

