# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: InTheLoop.LoopEmail
PackageVersion: 6.18.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://dl.intheloop.io/Loop-Email-Setup.exe
  InstallerSha256: B198B29B38436746AFAB23CAF3282342209025A8C6A8B83B43F9CE20DD4E5029
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://dl.intheloop.io/Loop-Email-Setup.exe
  InstallerSha256: B198B29B38436746AFAB23CAF3282342209025A8C6A8B83B43F9CE20DD4E5029
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
