# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: TeamViewer.TeamViewerHost
PackageVersion: 15.21.8
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe
  InstallerSha256: 51A136A321603E519110A3FB1CDF42D9B791202AED3592F6CA92891E249236E2
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

