# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KDE.Kate
PackageVersion: 21.08.1
MinimumOSVersion: 10.0.0.0
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1418/artifact/kate-21.08.1-1418-windows-msvc2019_64-cl.exe
  InstallerSha256: 6D2291E55A371B1F908775484ED1F93E940DE08B10D8DF59A29703DFE7BB85B6
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
