# Automatically updated by the winget bot at 2021/Sep/22
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.135.5004
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
    MinimumVersion: 10.0.40219
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29325.2
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
    MinimumVersion: 14.28.29325.2
Installers:
- Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: burn
  Scope: machine
  InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
  InstallerSha256: F89B53CE317B8E7CECF41DB7F1A2F3823BC4DC1C79BAA5EF2A69D0E5A0FE64B7
  UpgradeBehavior: install
  ProductCode: '{c7419ead-1601-4700-b35a-15cccf84a7d2}'
ManifestType: installer
ManifestVersion: 1.0.0
