# Automatically updated by the winget bot at 2021/Sep/22
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.135.5004
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
