# Created with YamlCreate.ps1 v2.0.4 $debug=NVS1.5-1-19041-1320
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: valinet.ExplorerPatcher.Prerelease
PackageVersion: 22000.348.40.10
MinimumOSVersion: 10.0.0.0
InstallerType: inno
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/valinet/ExplorerPatcher/releases/download/22000.348.40.10_dfd7030/ep_setup.exe
  InstallerSha256: 90EDB4098011B6BB4414F1E66D38AE3576ABE47E194B0EDE91B72FAC2D078DE4
  ProductCode: '{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_ExplorerPatcher'
ManifestType: installer
ManifestVersion: 1.1.0
