# Automatically updated by the winget bot at 2021/Sep/23
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: DigiDNA.iMazing
PackageVersion: 2.14.3.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://downloads.imazing.com/windows/iMazing/iMazing2forWindows.exe
  InstallerSha256: 28603DD934D25431A30D29E0E57A6A2FF00C8CF7C14CA285D1EDE7C1848BE948
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
