# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: OpenJS.NodeJSLTS
PackageVersion: 14.17.6
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v14.17.6/node-v14.17.6-x64.msi
  InstallerSha256: E72CEB05C7596A6E381172369DCE1C374A2B09EE739DCA330BE58F3977B5C03D
  ProductCode: "{402B92D4-F32A-4800-87F6-45784E450326}"
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v14.17.6/node-v14.17.6-x86.msi
  InstallerSha256: 5A8225D7DBBE5707B183E89C2FF779A9DB7826A94F83D99CD6C879EC60044C3F
  ProductCode: "{79614FE0-A31B-45CE-A36B-2901DA79894C}"
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

