# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: PaulPacifico.ShutterEncoder
PackageVersion: "15.3"
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://www.shutterencoder.com/Shutter%20Encoder%2015.3%20Windows%2064bits.exe
  InstallerSha256: C9675474DABF31E2A92BAFFBEF2B163CC58BEAE2EFC9A34533A43E6328D1B0F0
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
