# Automatically updated by the winget bot at 2021/Sep/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Microstockr.Desktopapp
PackageVersion: 2.3.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://microstockr.com/downloads/MicrostockrSetup.exe
  InstallerSha256: E16F3A3785722C31A0AC8016E0A645186E208D4F8115AEF76EF9B0FD51560DC0
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
