# Created with YamlCreate.ps1 v2.0.4 $debug=QUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Logseq.Logseq
PackageVersion: 0.5.4
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
FileExtensions:
- md
- org
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/logseq/logseq/releases/download/0.5.4/Logseq-win-x64-0.5.4.exe
  InstallerSha256: 61F49B568A94BCFDE35BC5361D05A74805373F4F1DC0A96C3A4AE2D3C0554053
  ProductCode: Logseq
ManifestType: installer
ManifestVersion: 1.1.0
