# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.2019.TeamExplorer
PackageVersion: 16.11.2
PackageName: Visual Studio Team Explorer 2019
Publisher: Microsoft Corporation
PackageUrl: https://visualstudio.microsoft.com/
License: Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription: A free solution for non-developers to interact with Team Foundation Server and Visual Studio Team Services.
LicenseUrl: https://visualstudio.microsoft.com/license-terms/
Moniker: vs2019-teamexplorer
Tags:
- C++
- vs
- C#
Commands:
- devenv
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/bacf7555-1a20-4bf4-ae4d-1003bbc25da8/4a91817eee53e525dbfd5f02bd00b385f9089cacae7482737b6e4c99d0ed5935/vs_TeamExplorer.exe
  InstallerSha256: 4A91817EEE53E525DBFD5F02BD00B385F9089CACAE7482737B6E4C99D0ED5935
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --passive
    Custom: --wait --productId Microsoft.VisualStudio.Product.TeamExplorer --channelId VisualStudio.16.Release --channelUri https://aka.ms/vs/16/release/channel --add Microsoft.VisualStudio.Workload.Universal
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

