# Automatically updated by the winget bot at 2021/Aug/26
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: NimbusWeb.NimbusNote
PackageVersion: 6.45.13
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://nimbusweb.me/nimbusnote.exe
  InstallerSha256: 2F0CDEB0429B97BF304F160DE046FE860F9E533087915C1C843645B5A995CC82
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  Scope: user
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
