# Created using wingetcreate 0.3.0.6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Lexikos.AutoHotkey
PackageVersion: 1.1.33.10
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
FileExtensions:
- ahk
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  InstallerUrl: https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.33.10/AutoHotkey_1.1.33.10_setup.exe
  InstallerSha256: 8972DF169A3CD8ABC37DE9122D54B9270D1B5FE277DD727642224FDC76F8F52D
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
ManifestType: installer
ManifestVersion: 1.0.0

