# Automatically updated by the winget bot at 2021/Sep/24
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.97.801.0
MinimumOSVersion: 8.1.0.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
    MinimumVersion: 92.0.902.84
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  InstallerType: exe
  InstallerSha256: 74418DE06C21F2C137345ADC71EEAFE4E5F4DD3D504F0FF0A305DC3592C6693D
  Scope: machine
  InstallerSwitches:
    Custom: -norestart ACCEPT_EULA=1
    Silent: -quiet
    SilentWithProgress: -passive
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup.exe
  InstallerType: exe
  InstallerSha256: 7AB78E6AE08F4C5364FB7186B5FBF77BE23E667F4272EBDB6232FC6C4AFACC0A
  Scope: machine
  InstallerSwitches:
    Custom: -norestart ACCEPT_EULA=1
    Silent: -quiet
    SilentWithProgress: -passive
ManifestType: installer
ManifestVersion: 1.0.0
