# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: KDE.KDEConnect
PackageVersion: 21.08.1.722
PackageLocale: en-US
Publisher: KDE e.V.
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: KDE Connect
PackageUrl: https://kdeconnect.kde.org/
License: GNU GPLv2/GNU GPLv3
LicenseUrl: https://www.gnu.org/licenses/gpl-2.0.html
# Copyright: 
# CopyrightUrl: 
ShortDescription: Enabling communication between all your devices. Made for people like you.
# Description: 
Moniker: kdeconnect
Tags:
- android
- phone
- connect
- kde
- k
ManifestType: defaultLocale
ManifestVersion: 1.0.0
