# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: calibre.calibre
PackageVersion: 5.27.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- lit
- mobi
- azw
- epub
- azw3
- fb2
- fbz
- docx
- html
- prc
- odt
- rtf
- pdb
- txt
- pdf
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v5.27.0/calibre-5.27.0.msi
  InstallerSha256: F83111F93623690D905FDB85C168BB7068D3F0CB336A3A6F1B22B343BD627E2B
  UpgradeBehavior: install
  ProductCode: "{F8B80815-02B9-41C3-88C4-DA539BDC1635}"
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v5.27.0/calibre-64bit-5.27.0.msi
  InstallerSha256: 738AAF1056EB39484ACEB4ADEB9F610569DACB52317180B337658E1683E0AE28
  UpgradeBehavior: install
  ProductCode: "{B416F722-2ABE-4B66-A430-D5C51D556589}"
ManifestType: installer
ManifestVersion: 1.0.0

